name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    name: run golangci-golint on the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1'

      - run: go version

      - uses: actions/checkout@v3

      - name: golangci-golint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2
          ./bin/golangci-lint run -v ./...
