name: tests
on:
  push:
  pull_request:

jobs:
  test:
    name: run tests with code coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.20"
          - "1.19"

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true

      - run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: go test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          env_vars: GO
        env:
          GO: ${{ matrix.go }}
